### ISSUE TITLE
Incorrect Type for type apolloError

### ISSUE THREAD

**Issue by bihnkim** [apollographql/reason-apollo#102]
```
type apolloError = {
  .
  "message": string,
  "graphQLErrors": Js.Nullable.t(array(string)),
  "networkError": Js.Nullable.t(string)
};
```

The above type for apolloError's `graphQLErrors` is incorrect. It should be:

```Js.Nullable.t(array(graphQLErrors))```

**Comment by Gregoirevda** [comment]
merged https://github.com/apollographql/reason-apollo/pull/112
