### ISSUE TITLE
Already provide Mutation parsed result

### ISSUE THREAD

**Issue by grsabreu** [apollographql/reason-apollo#105]
Currently with the mutation imperative API the `mutate` function returns `Js.Promise.t(Json.t)` and the user needs to parsed manually with `convertJsInputToReason`. I think this additional step is not necessary and it could return just `Js.Promise.t(Mutation.t)`.

What do you think?

cc @georgelima

**Comment by Gregoirevda** [comment]
@grsabreu  This is now typed as [Js.Promise.t(renderPropObjJS)](https://github.com/apollographql/reason-apollo/blob/master/src/graphql-types/ReasonApolloMutation.re#L36) , but asked to be changed [here](https://github.com/apollographql/reason-apollo/pull/132) to `Js.Promise.t(executionResult)`

**Comment by Enalmada** [comment]
@grsabreu @svsool Do you have opinion on https://github.com/apollographql/reason-apollo/issues/105 Js.Promise.t(executionResult) vs Js.Promise.t(Mutation.t)?  It would be nice to take action on the concept.

**Comment by grsabreu** [comment]
@Gregoirevda I really liked that `executionResult`!

**Comment by grsabreu** [comment]
Already fixed by https://github.com/apollographql/reason-apollo/pull/164
