### ISSUE TITLE
Response includes field name that starts with uppercase letter

### ISSUE THREAD

**Issue by arecvlohe** [apollographql/reason-apollo#107]
## Description

Not able to access field on nested object when object contains field names that start with an uppercase letter. The response from the API looks like this:

```
{
  "data": {
    "Link": {
      "id": "cji9huoi5ob0o01032yhfsz9b",
      "title": "News from Indian Country"
    }
  }
}
```

In my query component I have:
```
Data(response) =>
```

If I try to access the link title I would do: 
```
response##Link##title
```

However, I get this error: 
```
[bucklescript] Js object ## expect syntax like obj##(paint (a,b))
```

I looked at transformers in the Apollo client docs but can't figure out how I would do it here to modify `Link` to be `link` instead. If anyone has a solution it would be greatly appreciated.

## Related Issue
BuckleScript/bucklescript#2066

**Comment by Gregoirevda** [comment]
You can use an alias to fix this:
```
{
    link: Link {
      id
      title
    }
}
```
Could you add a PR in the FAQ's README please?

**Comment by arecvlohe** [comment]
@Gregoirevda Thanks, will do!
