### ISSUE TITLE
apolloLinkErrorResponse##networkError confusing typing

### ISSUE THREAD

**Issue by couchemar** [apollographql/reason-apollo#110]
Hi there!
I am trying to get `networkError##statusCode` in error link function:
```
let errorLink = {
  let errorHandler =
      (errorResponse: ReasonApolloTypes.apolloLinkErrorResponse) => {
    let networkError: option(ReasonApolloTypes.networkError) = errorResponse##networkError;
    switch networkError {
      | Some(error: ReasonApolloTypes.networkError) => Js.log(error##statusCode);
      | None => ()
    }
  };
  ApolloLinks.createErrorLink(errorHandler);
};
```
This code compiles quite fine but in runtime, `error` get `undefined` value, and error  `Uncaught TypeError: Cannot read property 'statusCode' of undefined` occurs.

What's wrong with this code? And how to get `statusCode`?

**Comment by Gregoirevda** [comment]
The networkError is just a regular Javascript `Error`. It can contain anything. 
There's an error in `errorResponse##networkError` it's an option, but should be an `Js.Nullable.t`

I opened a pull request: https://github.com/apollographql/reason-apollo/pull/112

**Comment by couchemar** [comment]
Thanks! now error handling more clear!
I'll close issue

**Comment by Gregoirevda** [comment]
Did you tried error handling in your app by pointing to the PR branch?

**Comment by couchemar** [comment]
Yes, I am tried PR branch with error link:
```
let errorLink = {
  let errorHandler = (errorResponse: ReasonApolloTypes.errorResponse) =>
    switch (Js.Nullable.toOption(errorResponse##networkError)) {
    | Some(ne) => Js.log(ne##statusCode)
    | None => ()
    };
  ApolloLinks.createErrorLink(errorHandler);
};
```
