### ISSUE TITLE
bs-platform 4.0.0

### ISSUE THREAD

**Issue by studious** [apollographql/reason-apollo#116]
Hi team.

Do you have a timeframe for `bs-platform 4.0.0`? We started to upgrade and noticed you are pinned to 3.

Thanks

**Comment by studious** [comment]
@Gregoirevda any news on supporting `bs-platform 4.0.0`?

**Comment by Enalmada** [comment]
I have a sample project I have working on windows with next.js bindings and bs-platform 4.0.5.  I assume most people considering adopting reason are probably going to be on 4 now so this could start hurting adoption.  If I try and roll bs-platform back to 3, I get errors: 
```
[5/10] Building bindings\Next.mlast
FAILED: bindings/Next.mlast 
C:\Users\Adam\code\gell\prototypes\with-reasonml-apollo\node_modules\bs-platform\lib\bsc.exe -pp "C:\Users\Adam\code\gell\prototypes\with-reasonml-apollo\node_modules\bs-platform\lib\refmt.exe --print binary" -ppx "C:\Users\Adam\code\gell\prototypes\with-reasonml-apollo\node_modules\bs-platform\lib\reactjs_jsx_ppx_2.exe"   -w -30-40+6+7+27+32..39+44+45+101 -bs-suffix -nostdlib -I "C:\Users\Adam\code\gell\prototypes\with-reasonml-apollo\node_modules\bs-platform\lib\ocaml" -bs-super-errors -no-alias-deps -color always -c -o bindings\Next.mlast -bs-syntax-only -bs-binary-ast -impl C:\Users\Adam\code\gell\prototypes\with-reasonml-apollo\bindings\Next.re
File "C:\Users\Adam\code\gell\prototypes\with-reasonml-apollo\bindings\Next.re", line 17, characters 10-16:
Error: 2967: <UNKNOWN SYNTAX ERROR>
```

This is stopping me from being able to continue building out my reason-apollo with next.js learning project.  I am just beginning to learn about reason and apollo but I am likely to become a contributor in the near future if you could be so kind as to update the dependencies and do a release.

**Comment by thangngoc89** [comment]
I'm currently using reason-apollo eith bs-platform 4.0. except from annoying warnings, I don't have any issues. so updating is nice but it should work regardless

**Comment by Enalmada** [comment]
Thanks @thangngoc89, that is extremely helpful to know.  It should be an easy update and more importantly, it's not a blocking issue.  Phew...I can put up with some warnings.

**Comment by johnhampton** [comment]
Does `bs-platform 4` really need to be declared as a peer dependency? Most instructions have it installed as a dev dependency.

**Comment by thangngoc89** [comment]
@johnhampton it's a peer dependency for a library like this one.

**Comment by Baransu** [comment]
Because https://github.com/apollographql/reason-apollo/pull/133 got merged this issue can probably we closed 🙂

cc @Gregoirevda

**Comment by Gregoirevda** [comment]
I just published it on npm @baransu. Thanks for the upgrade @MarcelCutts 
https://github.com/apollographql/reason-apollo/releases/tag/reason-apollo%400.14.0
