### ISSUE TITLE
Allow ApolloClient to be more configurable

### ISSUE THREAD

**Issue by emmenko** [apollographql/reason-apollo#13]
Hey guys,

first of all thanks a lot for having some basic bindings of Apollo.
I'm just getting started with Reason and I'm trying it out in a current project of mine, so I'm still new to a lot of things and I'm still trying to understand how everything works.
Having already some bindings and code to look at is helping me a lot to figure out things.

I also really like the declarative components approach taken here instead of the classic HoC of `react-apollo`.

With that said, I'd like to know what are the plans for this library. For example, at the moment when you create a new instance of Apollo Client you can only pass the `uri` for the `http-link`.
Most of the time you also need other links (e.g. auth header, error, ...).
It would be nice to have this more configurable, e.g. you can easily create other links (given their bindings) and pass them to Apollo Client constructor.
Furthermore to also make things like e.g. `InMemoryCache` configurable.

For now I was able [to do that myself](https://github.com/emmenko/tourname/pull/14) by basically creating a new ApolloClient module and overriding some things, but it would be nice to have this out of the box.

If you'd like I can also try to contribute, probably with some help needed 😇

Thanks a lot 🙏

**Comment by Gregoirevda** [comment]
Hey,
Thanks for the feedback! Yes, the client should be much more configurable. I'd appreciate a PR that extract the client and adds the minimum constructor for http and cache. I'll start the implementation early 2018

**Comment by emmenko** [comment]
What I did in my project is like this: https://github.com/emmenko/tourname/blob/master/packages/web-app/src/Apollo.re#L112-L165

Not sure if it's the "right" API though, you probably have more insights.

**Comment by Gregoirevda** [comment]
I guess we can close this now, since https://github.com/apollographql/reason-apollo/pull/16 has been merged
