### ISSUE TITLE
Wrong type for apollo-link errorResponse

### ISSUE THREAD

**Issue by bsr203** [apollographql/reason-apollo#137]
Please see the type as defined by apollo-link source [here](https://github.com/apollographql/apollo-link/blob/master/packages/apollo-link-error/src/index.ts#L12)

```
export interface ErrorResponse {
  graphQLErrors?: ReadonlyArray<GraphQLError>;
  networkError?: Error;
  response?: ExecutionResult;
  operation: Operation;
  forward: NextLink;
}
```

the reason binding is defined as [here](https://github.com/apollographql/reason-apollo/blob/master/src/ReasonApolloTypes.re#L49)

```
type errorResponse = {
  . 
  "graphqlError": Js.Nullable.t(Js.Array.t(graphqlError)),
  "networkError": Js.Nullable.t(networkError),
  "response": Js.Nullable.t(executionResult),
  "operation": operation ,
  "forward": operation => subscription,
};
```

so the key name has to change from `graphqlError` to `graphQLErrors`

**Comment by Gregoirevda** [comment]
Thanks for the clear issue! Don't hesitate to open other issues if you encounter other problems ;)
