### ISSUE TITLE
Nested (optional) input types

### ISSUE THREAD

**Issue by Willianvdv** [apollographql/reason-apollo#144]
Given I have a `users` connection that accepts an input type that accepts a `where` argument, this `where` input type has a couple of optional arguments. With GraphQL, you can query like so:
```
query {
  usersCalledLee: users(where: { firstName: { _eq: "lee" }})
  usersThatAreBots: users(where: { bot: { _eq: true  })
}
```

In my reason-apollo app, the user can specify these filters and so the where is constructed in my app and passed via the query's variables to the appropriate connection.

```
module GetUsers = [%graphql
  {|
  query GetUsers($where: WhereInput!){
    reports(first: 100, where: $where }) {
      ...
    }
  }
|}
];
```

In order to construct the `where`, I have to specify all the Some and None values so it matches the type.
```
let where = {
  username: Some({_eq: "lee"})
  bot: None
}
```

Here's the problematic part, when I use this `where` as variables for the query, this `None` will be transformed to `nil` and send to the GraphQL server. As `nil` isn't valid input, the server will return a 500. 

I'm quite new to the Reason and Apollo game, but I guess the fix for this case would be to use `{}` rather than `nill` as `None` value or remove the entries that have a `None` value.

What do you think?

**Comment by baransu** [comment]
That's an issue in `graphql_ppx` that `reason-apollo` is using. You can track it here: https://github.com/mhallin/graphql_ppx/issues/59.

**Comment by Willianvdv** [comment]
Thanks for your reply @baransu! I'll track that issue.

**Comment by Willianvdv** [comment]
@baransu I saw that glennsl/bs-json/issues/50 got resolved, but I have troubles understanding how I can apply this. Can you help me how I can omit the null values from the `where` I've posted in the example?

**Comment by baransu** [comment]
The issue still exists in https://github.com/mhallin/graphql_ppx/issues/59. Please check my latest comment. I know how this could be fixed but I'm missing knowledge about OCaml AST generation and how to implement it.
