### ISSUE TITLE
Integrating with graphql_ppx

### ISSUE THREAD

**Issue by thangngoc89** [apollographql/reason-apollo#15]
I have tried to integrate reason-apollo with graphql_ppx for a better dev experience like auto linting the query, auto type definition,...

This is what I've done so far https://github.com/thangngoc89/reason-apollo 

It's a fork of this repo and maintaining a fork isn't something I want to do. So I hope it could be somehow make it back to this repo

**Comment by Gregoirevda** [comment]
Thanks for sharing! I'll take a look tomorrow

**Comment by emmenko** [comment]
> It's a fork of this repo and maintaining a fork isn't something I want to do. So I hope it could be somehow make it back to this repo

We should definitely do this yes!

Maybe can you guys explain a bit the idea and the steps to take for integrating the ppx part? It would be really helpful to understand this a bit more and to help out.

**Comment by Gregoirevda** [comment]
In PR, Query has the same usage as your example @thangngoc89.
Mutation is added too, would be better to be able to add the parser in the Children as a function 3th argument, but don't think it's possible.

https://github.com/apollographql/reason-apollo/pull/18

Please leave some comments in the PR before I merge it
