### ISSUE TITLE
Example needed: how to use Upload API

### ISSUE THREAD

**Issue by nlfiedler** [apollographql/reason-apollo#151]
So the `apollo-upload-client` is available now, but I can't figure out how to use it with reason-apollo. First there's the trick of getting the `File` object from the `input` element into the mutation variables, which I'm pretty sure I'm not doing correctly, and then I get a strange GraphQL error about `Path` not being defined. So docs or an example for the upload API would be super helpful. Thanks.

**Comment by nlfiedler** [comment]
I'm going to guess that converting the `File` object to JSON is the wrong approach, and that somewhere in `extract-files` it's failing to read the file. For now I'm hacking around this with raw JavaScript (see `runMutate` in https://gist.github.com/nlfiedler/0da484d9009ea190dc039c3c10d4a390), but would like to avoid that some day.

**Comment by tmattio** [comment]
I haven't been able to make it work without raw Js either. Would be great to have an example!

@heygema Would you have a public repo that uses this? If not any insights would be really appreciated <3

**Comment by heygema** [comment]
hi, sorry for the late reply!

so if you want to use the createUploadLink, you need to replace the createHttpLink with createUploadLink.

```
/* Create an InMemoryCache */
let inMemoryCache = ApolloInMemoryCache.createInMemoryCache();

/* Create an HTTP Link from the README example replaced by createUploadLink */
let uploadLink =
  ApolloLinks.createUploadLink(~uri="http://localhost:3010/graphql", ());

let instance =
  ReasonApollo.createApolloClient(~link=uploadLink, ~cache=inMemoryCache, ());
```

are you able to get this working?
if not can you tell me what's the path error says?

thanks, and hope this helps!

**Comment by Gregoirevda** [comment]
@heygema thanks for explaining, could you add an example in `examples/simpleExample` please?

**Comment by nlfiedler** [comment]
The piece that I'm missing is how to pass the file to `EditUser.make()` when you're ready to post the mutation.

**Comment by nlfiedler** [comment]
Thank you for that guidance. I went wrong somewhere and tried to define a file type, but really should have been using `Js.Json.t` throughout. After changing that, it all came together.
