### ISSUE TITLE
Unreliable networkStatus field

### ISSUE THREAD

**Issue by couchemar** [apollographql/reason-apollo#161]
The `networkStatus` field in query/mutation result could be missing. There are some issues in `apollo-client` and `apollo-link` about this:
https://github.com/apollographql/apollo-link/issues/300
https://github.com/apollographql/apollo-client/issues/4057
https://github.com/apollographql/apollo-link/issues/536

**Issue Labels**

- [ ] has-reproduction
- [ ] feature
- [ ] docs
- [ ] blocking
- [ ] good first issue

**Comment by grsabreu** [comment]
So the fix is to make it Js.Nullable.t
