### ISSUE TITLE
Support for optimistic updates

### ISSUE THREAD

**Issue by mbirkegaard** [apollographql/reason-apollo#170]
**Issue Labels**

- [ ] has-reproduction
- [x] feature
- [ ] docs
- [ ] blocking
- [ ] good first issue

Are there any ways of doing optimistic updates akin to https://www.apollographql.com/docs/react/features/optimistic-ui.html?

```
<Mutation mutation={UPDATE_COMMENT}>
    {mutate => {
      <Comment
        updateComment={({ commentId, commentContent }) =>
          mutate({
            variables: { commentId, commentContent },
            optimisticResponse: {
              __typename: "Mutation",
              updateComment: {
                id: commentId,
                __typename: "Comment",
                content: commentContent
              }
            }
          })
        }
      />;
    }}
  </Mutation>
```

Since the type of `apolloMutation` is 
```
  type apolloMutation =
    (~variables: Js.Json.t=?, ~refetchQueries: array(string)=?, unit) =>
    Js.Promise.t(renderPropObjJS);
```
I wouldn't think so.

Anyone working on this?

If not, I'd I'd be happy to give it a go. 

As far as I can tell `optimisticResponse` should (when passed to the underlying JS) be the JSON-encoding of type `t` in the module produced by `graphql_ppx`, using a sort of reverse of `parse` in that module, but I haven't looked deep enough in that repo to know what's possible out of the box.

**Comment by MoOx** [comment]
I guess https://github.com/apollographql/reason-apollo/commit/9fc639ff526819117f71e16bf995c80a5b59387d closed this issue ?!

**Comment by Gregoirevda** [comment]
@MoOx Indeed
