### ISSUE TITLE
Update `subscriptions-transport-ws` dependency for graphql 14 support

### ISSUE THREAD

**Issue by skaldarnar** [apollographql/reason-apollo#185]
Hi, 

I'm trying to use `reason-apollo@^0.15.2` with `graphql@^14.x.y`. Due to the dependency on `subscriptions-transport-ws@0.9.0` in `reason-apollo` I get the following peer dependency warning:
```
reason-apollo > subscriptions-transport-ws@0.9.0" has incorrect peer dependency "graphql@^0.10.0 || ^0.11.0"
```

I see that newer versions of `subscriptions-transport-ws` have their peer dependencies updated to also work with `graphql` >14. Is there anything blocking a version bump of   `subscriptions-transport-ws` to [0.9.15](https://github.com/apollographql/subscriptions-transport-ws/releases/tag/v0.9.15)?

**Comment by Gregoirevda** [comment]
Seems to be fixed in @alpa release `yarn upgrade reason-apollo@alpha`
