### ISSUE TITLE
Uncaught Error: You must wrap the query string in a "gql" tag.

### ISSUE THREAD

**Issue by drejohnson** [apollographql/reason-apollo#19]
I'm not sure if I'm doing something wrong but I can't get the graphql_ppx update to work. Throws error in console:

```
Uncaught Error: You must wrap the query string in a "gql" tag.
    at QueryManager.query (http://localhost:3333/index.js:40843:19)
    at ApolloClient.query (http://localhost:3333/index.js:40327:34)
    at sendQuery (http://localhost:3333/index.js:41814:57)
    at newrecord.(anonymous function) (http://localhost:3333/index.js:41843:9)
    at Object._1 (http://localhost:3333/index.js:543:12)
    at Object.componentDidMount (http://localhost:3333/index.js:1293:117)
    at Object.chainedFunction [as componentDidMount] (http://localhost:3333/index.js:37557:11)
    at commitLifeCycles (http://localhost:3333/index.js:25512:24)
    at commitAllLifeCycles (http://localhost:3333/index.js:26688:9)
    at HTMLUnknownElement.callCallback (http://localhost:3333/index.js:17284:14)
index.js:26489 
The above error occurred in the <ReasonApollo> component:
    in ReasonApollo (created by App)
    in App (created by Home)
    in div (created by Home)
    in Home
    in div (created by App)
    in App
```

Here's my repo: https://github.com/drejohnson/reason-apollo-graphql_ppx-test

I also get this warning in terminal:

```
Warning number 102
[0]   /home/dre/workspaces/PHRESHR/reason-apollo-graphql_ppx-test/node_modules/reason-apollo/src/graphql-types/ReasonApolloQuery.re64:11-43
[0]
[0]   62 ┆   },
[0]   63 ┆ willReceiveProps: ({state, reduce}) => {
[0]   64 ┆   if(q##variables != state.variables) {
[0]   65 ┆     sendQuery(~query=q, ~reduce);
[0]   66 ┆     state;
[0]
[0]   polymorphic comparison introduced (maybe unsafe)
```

**Comment by Gregoirevda** [comment]
Thanks for pointing this out!
Made a PR and pushed on npm
https://github.com/apollographql/reason-apollo/pull/20

**Comment by Gregoirevda** [comment]
Still need to fix the `polymorphic comparison introduced (maybe unsafe)` error, but this is less urgent. Could you help me with that? Cheng Lou: `It means you need to write a custom comparator`

**Comment by maarekj** [comment]
May be that a variable comparison function should be set as a props.

**Comment by janicduplessis** [comment]
I noticed that re-rendering with different params is currently broken, might be related to this. For now I just changed https://github.com/apollographql/reason-apollo/blob/master/src/graphql-types/ReasonApolloQuery.re#L65 to ref equality (===) but it will probably cause the component to always refetch even if nothing changed.

**Comment by Gregoirevda** [comment]
@janicduplessis We probably don't want that. Can't we make a Js comparison? 
`-external asJsObject : 'a => Js.t({..}) = "%identity";`
`asJsObject(props) == asJsObject(nextProps)`

**Comment by maarekj** [comment]
@Gregoirevda 
Compare via js comparison is the same thing that to compare via ref equality in reason. No ?

**Comment by janicduplessis** [comment]
@Gregoirevda Yea I agree, I'm not 100% sure of how equality works in bucklescript / reason so I can't tell if that would work. If we really need to provide a comparison function it would be nice to have it generated by graphql_ppx like you said to avoid the boilerplate.

**Comment by Gregoirevda** [comment]
@maarekj In JS you don't need a type signature to shallow compare 2 objects.
react-apollo is doing it like so: https://github.com/apollographql/react-apollo/blob/master/src/graphql.tsx#L207
We could `import shallowEqual from 'fbjs/lib/shallowEqual';` that should work...?

**Comment by maarekj** [comment]
@Gregoirevda Okay, using shallowEqual should probably work.

```reason
[@bs.module]
external shallowEqual : (Js.t({..}), Js.t({..}) => bool = "fbjs/lib/shallowEqual";
external asJsObject : 'a => Js.t({..}) = "%identity";

shallowEqual(asJsObject(q##variables), asJsObject(state.variables));
```

**Comment by thangngoc89** [comment]
@maarekj It should be 

```
[@bs.module]
external shallowEqual : (Js.t({..}), Js.t({..}) => Js.bool = "fbjs/lib/shallowEqual";
```

**Comment by Gregoirevda** [comment]
@thangngoc89 not sure about the Js.bool: https://bucklescript.github.io/docs/en/boolean.html#tips-tricks

**Comment by Gregoirevda** [comment]
Let's close this: https://github.com/apollographql/reason-apollo/pull/32

**Comment by Gregoirevda** [comment]
@maarekj indeed, the `==` in JS wouldn't have solved it.

**Comment by thangngoc89** [comment]
@Gregoirevda ah. So bucklescript to smart enough to convert it from Js.boolean to bool underhood.

**Comment by Gregoirevda** [comment]
yep

**Comment by Gregoirevda** [comment]
https://github.com/apollographql/reason-apollo/pull/32
