### ISSUE TITLE
Multiple GraphQL clients in one app

### ISSUE THREAD

**Issue by leomayleomay** [apollographql/reason-apollo#193]
**Is it possible to have 1+ clients in one app?**

I am trying to include 1+ clients in an app, one is for querying Github, another is for querying from my own graphql endpoint, it's not working quite well since every time I run `yarn send-introspection-query` to one of the endpoints, it will overwrite another one, which means I could have two schemas existed at the same time

**Comment by Gregoirevda** [comment]
You could use schema stitching or delegation to combine multiple gql schemas into one

**Comment by leomayleomay** [comment]
@Gregoirevda cheers, will try it out

**Comment by Gregoirevda** [comment]
But normally you should be able to do that, since you can pass an optional ApolloClient to a Query.
I'm wondering how apollocodegen manages that

**Comment by leomayleomay** [comment]
@Gregoirevda the problem is the graphql_schema.json fetched from my endpoint and the github endpoint, I am still looking for a way of  merging/stitching them into one :), otherwise, my ReasonReact app won't compile
