### ISSUE TITLE
 accept connectionParams in webSocketLink for adding headers

### ISSUE THREAD

**Issue by wawhal** [apollographql/reason-apollo#198]
Currently the `webSocketLink` function only accepts `uri` and `reconnect`. `connectionParams` of type `Js.Json.t` must also be accepted because almost always you would want to add headers to your webSocket connection.

**Issue Labels**

- [ ] has-reproduction
- [x] feature
- [ ] docs
- [ ] blocking
- [ ] good first issue

**Comment by Gregoirevda** [comment]
Pubilshed under 0.16.4
