### ISSUE TITLE
[Examples] How to re-use existing JS-created Apollo client (and vice-versa)

### ISSUE THREAD

**Issue by sgrove** [apollographql/reason-apollo#22]
Since integrating with existing projects is such a strong focus for Reason, it'd be great to have an example in the README to cover the case where my apollo client is created in JS-land and I want to use that from Reason-land.

Also vice-versa, in case that has any benefits, would be good to show how to share the Reason-created apollo-client with the JS components that expect it to be available.

Also asking because I need this and I'm not sure how to go about it!

**Comment by grsabreu** [comment]
@sgrove afaik this project focuses on 100% Reason approach to get started with Apollo. 
To allow a transition migration here in my company we developed another solution that allows you to use the same Apollo Client instance you are already using in your JS project https://github.com/Astrocoders/bs-reason-apollo.
I plan to add this weekend a demo to show how it goes

**Comment by Gregoirevda** [comment]
@grsabreu I was about to mention your library that focuses on apollo integration from a ReactJS project. Since this will probably be asked more, I'll add a `JS` query and mutation component that gets the client from context (reason-apollo is not using context now, which is a good thing). I'll add a provider too. Will ping in here when PR is there

**Comment by simontegg** [comment]
Any update? is this waiting on #64?.  
bs-reason-apollo is good compromise but I'd rather use the official library before I convert our codebase over.

**Comment by Gregoirevda** [comment]
Bindings to react-apollo 2.1 have been published.
You can now create a Provider in Reason or JS around your app and use the `Query` and `Mutation` components in Reason!

**Comment by simontegg** [comment]
Thanks! I look forward to using this.
