### ISSUE TITLE
bs-platform@7.0.1

### ISSUE THREAD

**Issue by idkjs** [apollographql/reason-apollo#221]
**Issue Labels**

- [ ] has-reproduction
- [x] feature
- [ ] docs
- [ ] blocking
- [ ] good first issue

Any plans on doing anything with `bs-platform@7.0.1` yet? If so I could pull this branch on my fork. Seems to work but feedback would be good.

https://github.com/idkjs/reason-apollo/tree/bs_platform_7

**Comment by JasoonS** [comment]
It is working for me on bs-platform@7.0.1

**Comment by Gregoirevda** [comment]
Thanks a lot for the work @idkjs 
Created a PR from your branch and merged it. Will publish asap
