### ISSUE TITLE
graphql_ppx now exporting the type of `parse` output

### ISSUE THREAD

**Issue by thangngoc89** [apollographql/reason-apollo#23]
In the lastest commit, graphql_ppx allow accessing the type of parse function output with `Query.t`.

See it here https://github.com/mhallin/graphql_ppx/commit/50d0fd21dcd96e2baaf12c25940f41aa5ccde933

I can't remember why I needed this when implementing this in my fork but I remember this is pretty important somehow

**Comment by Gregoirevda** [comment]
It has been pushed to opam yet? version still on 0.0.1... dependency is `^0.0.1` so it should be possible to use latest features no?

**Comment by janicduplessis** [comment]
It is (opam update && opam upgrade graphql_ppx), just tried improving the API to use functors and manage the query creation part.

The API I want would need graphql_ppx to also define the type of the variables so it works properly, right now I'm just adding it to the generated module manually since it's usually a simple type.

The API I'm going for would look like:
```reason
module AppQuery = [%graphql {| ... |}];

module QueryRenderer = Client.Query.Create(AppQuery);

<QueryRenderer variables={"a": a}>...</Query>
```

**Comment by thangngoc89** [comment]
@janicduplessis I've asked for graphql_ppx to export the type of variables. But it's really hard to accomplished. Could you share your improvement? Because I'm not satisfy with the current API

**Comment by janicduplessis** [comment]
https://github.com/janicduplessis/reason-apollo

You can look at the last few commits, currently you have to add the type of variables manually since it’s not generated automatically. For the rest I’m pretty satisfied with the api.

```reason
Client.Query.Create({ include MyQuery; type vars = {. “a”: a }; });
```

**Comment by Gregoirevda** [comment]
Could you provide more details about the requirements please?
with `opam upgrade graphql_ppx` I was able to access `Query.t`, but I can't inside the jsx component in the library: 
https://github.com/apollographql/reason-apollo/commits/feature/graphql_ppx-parse-type

**Comment by Gregoirevda** [comment]
@janicduplessis bindings to react-apollo 2.1 are published. We now use a functor like you mentioned to create a Query. Parsing is done inside the Query component which is easier to work with.
