### ISSUE TITLE
PPX issue due to bs-platform

### ISSUE THREAD

**Issue by a-c-sreedhar-reddy** [apollographql/reason-apollo#239]
I just yarn added packages and updated `bsconfig.json`. This is the error at `open ReactNative;`
```
Failure("Ast_mapper: OCaml version mismatch or malformed input")
File "/home/a-c-sreedhar-reddy/Desktop/PlantApp/node_modules/.lsp/App.ast", line 1:
Error: Error while running external preprocessor
Command line: /home/a-c-sreedhar-reddy/Desktop/PlantApp/node_modules/graphql_ppx/ppx '/tmp/camlppxb80464' '/tmp/camlppxe0b3a9'
```

**Comment by a-c-sreedhar-reddy** [comment]
I downgraded my bs-platform to v5 from v7. I am new to ReasonML. Can someone upgrade?

**Comment by baransu** [comment]
If you want to use latest bs-platform please use https://github.com/reasonml-community/graphql_ppx

**Comment by Gregoirevda** [comment]
README has been updated and from version `0.20.0`, reason-apollo uses graphql_ppx from the reasonml community package
