### ISSUE TITLE
How can setContext be used?

### ISSUE THREAD

**Issue by a-c-sreedhar-reddy** [apollographql/reason-apollo#242]
How can this https://www.apollographql.com/docs/react/networking/authentication/#header be used in reason-apollo. Here https://github.com/apollographql/reason-apollo/blob/master/src/ApolloLinks.re#L18 
```
[@bs.module "apollo-link-context"]
external apolloLinkSetContext: (unit => Js.t({..})) => apolloLink =
  "setContext";
```
function in setContext does not accept any parameters where as headers are required. And also how can it be concate with httpLink?

**Comment by a-c-sreedhar-reddy** [comment]
Currently I have done this

```
/* Create an InMemoryCache */
[@bs.module "apollo-link-context"] external setContext: string = "setContext";
Js.log(setContext);
let inMemoryCache = ApolloInMemoryCache.createInMemoryCache();
let authLink = {
  %bs.raw
  {|ApolloLinkContext.setContext((_, { headers }) => {
  // get the authentication token from local storage if it exists
  const token = localStorage.getItem("token");
  // return the headers to the context so httpLink can read them
  return {
    headers: {
      ...headers,
      Authorization: token ? `JWT ${token}` : "",
    },
  };
})
|};
};

/* Create an HTTP Link */
let httpLink =
  ApolloLinks.createHttpLink(~uri="http://localhost:8000/graphql", ());

let instance =
  ReasonApollo.createApolloClient(
    ~link=[%bs.raw {| authLink.concat(httpLink) |}],
    ~cache=inMemoryCache,
    (),
  );
```

**Comment by a-c-sreedhar-reddy** [comment]
Can someone suggest me the correct way

**Comment by baransu** [comment]
Here is simple example how to set headers:
```reason
ApolloLinks.apolloLinkSetContext(_ =>
    functionToGetTokenFromLocalStorage()
    ->Option.map(token =>
        {
          "headers": {
            "Authorization": {j|Bearer $token|j},
          },
        }
      )
    ->Option.getWithDefault(Js.Obj.empty())
  );
```

**Comment by BlueHotDog** [comment]
this seems to not cover the actual signature which should be able to also accept a Promise, any idea how to address this?

**Comment by a-c-sreedhar-reddy** [comment]
@BlueHotDog You can try changing the signature and submit a PR.

**Comment by baransu** [comment]
@a-c-sreedhar-reddy @BlueHotDog You can change the signature to always use `Js.Promise.t` or create second binding which will be `apolloLinksAsyncSetContext`

**Comment by BlueHotDog** [comment]
I did just that for my code, was wandering if a PR is needed. I explored using GADT/bs.unwrap to make the signature better but none actually work(e.g have 1 function that's typed correctly). so it seems like the 2 functions seem the way to go. I'll try and open a PR
