### ISSUE TITLE
CreateContextLink doesn't send header

### ISSUE THREAD

**Issue by patcito** [apollographql/reason-apollo#26]
Hi,

I'm trying to send headers for auth but it doesn't seem to send anything, here's the gist of my apollo client https://gist.github.com/patcito/1a7f148ecadc65d9a1735f1fc350477e

Not sure what I'm missing. Any help appreciated.

Thanks

**Comment by Gregoirevda** [comment]
`ApolloInMemoryCache` and `ApolloLinks` methods have all been converted from functors to functions. Please `yarn upgrade reason-apollo@latest` and update with documentation :)

**Comment by patcito** [comment]
Ok I ran the upgrade and now my code looks like that https://gist.github.com/patcito/f5222c1e69a4d3422c4481031c8f474e

However, headers are still not being sent. Here's what is being sent:

```
Access-Control-Request-Headers:authorization,content-type
Access-Control-Request-Method:POST
Origin:http://localhost:3000
Referer:http://localhost:3000/
User-Agent:Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.71 Safari/537.36
```

It did add authorization so I guess there is progress Bearer. Thanks again.

**Comment by Gregoirevda** [comment]
Hey, just checked out and it's working for me: 
https://github.com/Gregoirevda/reason-apollo-todo-list

I've deleted `asJsObject` and will publish that later (wont cause the bug, but is overhead)

**Comment by Gregoirevda** [comment]
This might be your `OPTIONS` request method. Asking if the `authorization` header is accepted for the `POST`method your sending. So you probably have a 2nd request which is the actual graphql query with the correct headers

**Comment by patcito** [comment]
Thanks so much, works great.

**Comment by Gregoirevda** [comment]
Awesome, great to hear
