### ISSUE TITLE
ReasonApolloQuery willRecieveProps will not fire a sendQuery

### ISSUE THREAD

**Issue by Hehk** [apollographql/reason-apollo#34]
I am trying to update my render whenever the user changes a filter term. 
```re
let make = (~filter="", _children) => {
  ...component,
  render: _self => {
    let snippetQuery = SnippetQuery.make(~filter, ());
    <PageFrame>
      <Query query=snippetQuery>
```

The Query element re-renders on change but the graphql response does not. I believe this issue is caused by:
```re
willReceiveProps: ({state, reduce}) => {
  if(!shallowEqual(asJsObject(q##variables), asJsObject(state.variables))) {
    sendQuery(~query=q, ~reduce);
    state;
  } else {
    state;
  }
},
```
The sendQuery will never fire from a change in variables, the comparison on JavaScript objects does not appear to work in the way intended for this if block.

For example, If you run this in https://reasonml.github.io/en/try.html the output will be false no matter what the input objects are.
```re
type variables = {. "filter": string};
let x = {"filter": "test"};
let y = {"filter": ""};

Js.log(x != y);
```

Hopefully I am just using the system wrong but, if not, I am willing to make a PR to fix this issue.

**Comment by Gregoirevda** [comment]
Fixed?

**Comment by Hehk** [comment]
Yeah. It was fixed in the change in: https://github.com/apollographql/reason-apollo/commit/badba88241b40f99950ec1e66695237bfc06afb0
