### ISSUE TITLE
How to create infinite loading component

### ISSUE THREAD

**Issue by thangngoc89** [apollographql/reason-apollo#35]
I've been looking for create an infinite loading component. But it's very hard to do it with the current declarative API. I ended up cloning reason-apollo (again) to implement such feature. So I want to open an issue to discuss with you guys first before working on a PR. I see 2 possible ways to solve this:

1. Implement fetchMore like react-apollo. This adds complexity to the project 
2. Provide an imperative API so this kind of feature could be implemented in userland

**Comment by Gregoirevda** [comment]
`fetchMore` is probably the way to go, but it would be interesting to see a Component based approach... 
I need to work on the `apolloClient.query` subscriptions!

**Comment by thangngoc89** [comment]
I guess I need to do my homework to see how React Apollo does this. I'm using RR's state as a store for storing all the fetched data. It's hacky and probably inefficient because Apollo client already has its cache store.

**Comment by Gregoirevda** [comment]
yep, Apollo Client does all that work. We should just bind all the things

**Comment by thangngoc89** [comment]
Thank you for the tip. I'm gonna work on it.

**Comment by jeffutter** [comment]
Any update on this? I'm converting a react project that uses fetchMore and am wondering how to implement this.

**Comment by Gregoirevda** [comment]
We're binding react apollo 2.1 Query and Mutations components, so it will be fixed at that moment. Should be released very soon

**Comment by Gregoirevda** [comment]
bindings to react-apollo 2.1 have been published 🎉 enjoy
