### ISSUE TITLE
Better Error Information

### ISSUE THREAD

**Issue by patoncrispy** [apollographql/reason-apollo#42]
Whenever there is an error with a Mutation, all I get is a message saying[ 'an error occurred'](https://github.com/apollographql/reason-apollo/blob/master/src/graphql-types/ReasonApolloMutation.re#L32).

Would it be possible to simply pass the error returned from the Apollo Client mutation back so that it's easier to debug issues? I'm relatively new to a lot of this, so have no idea where to start debugging without proper error messages.

**Comment by Gregoirevda** [comment]
https://github.com/apollographql/reason-apollo/pull/45 not published yet
