### ISSUE TITLE
ApolloDevTools Setup

### ISSUE THREAD

**Issue by idkjs** [apollographql/reason-apollo#46]
Seems like ApolloDevTools isnt working when passed to client instance.

The error in devtools panel is:
```
Source map error: request failed with status 404
Resource URL: http://127.0.0.1:5500/examples/swapi/build/index.js
Source Map URL: utilities.js.map
```
This is the setup in this repos swapi example:

```re
module Instance =
  ReasonApollo.CreateClient(
    {
      let apolloClient =
        ReasonApollo.createApolloClient(
          ~cache=inMemoryCache /* restore method can be piped e.g. inMemoryCache |> restore(window.__APOLLO__) */,
          ~link=httpLink,
          ~connectToDevTools=Js.true_,
          ()
        );
    }
  );

```
First note is that you have to start a server for devtool to recognize the app, you cant just open index.html. I opened with [Live Server](https://ritwickdey.github.io/vscode-live-server/) in VS Code.

Once you get it open, running queries doesn't return anything. Im sure I have this set up incorrectly.

[![https://gyazo.com/de2633bd91aca75267b1316a62a2f18b](https://i.gyazo.com/de2633bd91aca75267b1316a62a2f18b.png)](https://gyazo.com/de2633bd91aca75267b1316a62a2f18b)

Response shows up in ui and in network tab:

[![https://gyazo.com/e98461eed9016c5c5287354a5eafcd81](https://i.gyazo.com/e98461eed9016c5c5287354a5eafcd81.png)](https://gyazo.com/e98461eed9016c5c5287354a5eafcd81)

Thanks.

**Comment by idkjs** [comment]
Have not looked at it since. I will take a look, let you know.

**Comment by idkjs** [comment]
Setting `connectToDevTools` to true gets you apollo dev tools in chrome.
```
//Client.re https://github.com/apollographql/reason-apollo/blob/e757cc8a0d1a8032522b50dd9f211d0354d0889b/examples/swapi/src/Client.re#L17
let instance =
  ReasonApollo.createApolloClient(
    ~link=httpLink,
    ~cache=inMemoryCache,
    ~connectToDevTools=true,
    (),
  );
```
<img width="519" alt="screen shot 2018-05-16 at 3 36 39 pm" src="https://user-images.githubusercontent.com/2370391/40120413-677ca0b4-591f-11e8-974e-7f2a48880710.png">

**Comment by Gregoirevda** [comment]
Thanks for looking it up!
