### ISSUE TITLE
Passing extra headers along the query

### ISSUE THREAD

**Issue by grabbou** [apollographql/reason-apollo#51]
Is there a way to pass additional headers along the query? Say I have authorized my user, I've obtained the token and looking into setting that on per query basis.

With regular Apollo client, this seems to be possible with: https://github.com/apollographql/apollo-link/tree/master/packages/apollo-link-http#passing-context-per-query

I've tried adding "context" to the client internally, but without luck.

**Comment by donut** [comment]
You can see how I've done it here: https://github.com/RightThisMinute/OCamURL-client/blob/master/src/apollo.re#L4-L7

**Comment by grabbou** [comment]
Thanks for pointing me to your solution. Right now, I ended up passing
"context" directly to `query` on the ApolloClient. Waiting for some
feedback before making a PR.

**Comment by Gregoirevda** [comment]
Hey! 
Would be good to have that available! 
I see that react-apollo new Query component doesn't have that feature yet (beta 2.1)
Optional prop in the Query component is probably the way to go right?

**Comment by grabbou** [comment]
Yup, I left you a lengthy message on Discord exploring various approaches - I am still getting started with Reason and Apollo itself.

The prop makes sense, but I ended up leaning towards accepting entire "context" object since it can contain other properties that might be needed.

**Comment by grabbou** [comment]
I ended up using @donut suggested and already supported solution - I somehow didn't understand the links referenced at first.

That said, I settled on the following being my `authLink`:
```ml
let contextHandler = () => {
  let token = Effects.getTokenFromStorage();
  {
    "headers": {
      "authorization": {j|Bearer $token|j}
    }
  };
};

let authLink = createContextLink(contextHandler);
```
