### ISSUE TITLE
Configuration for GraphQL subscriptions

### ISSUE THREAD

**Issue by bstro** [apollographql/reason-apollo#58]
I am reading documentation for this graphql subscriptions network interface for apollo called [subscription-transport-ws](https://github.com/apollographql/subscriptions-transport-ws) and it advises to install it in the following manner:

```
import { SubscriptionClient } from 'subscriptions-transport-ws';
import ApolloClient from 'apollo-client';

const GRAPHQL_ENDPOINT = 'ws://localhost:3000/graphql';

const client = new SubscriptionClient(GRAPHQL_ENDPOINT, {
  reconnect: true,
});

const apolloClient = new ApolloClient({
    networkInterface: client,
});
```

I don't see the `networkInterface` property supported by `ReasonApollo.createApolloClient`, however. I'm pretty new to Reason, so I feel I must be missing something. Is it possible to configure the networkInterface property when creating an `apolloClient`?

**Issue Labels**

- [ ] has-reproduction
- [x] feature
- [ ] docs
- [ ] blocking
- [ ] good first issue

**Comment by Gregoirevda** [comment]
We support subscriptions now
