### ISSUE TITLE
Query State Inconsistent

### ISSUE THREAD

**Issue by jatsrt** [apollographql/reason-apollo#59]
When you create a <Query/> component, the initial variables are set into state.  Theses are then checked as the incoming properties change to determine if the query should be re-executed.  

However, the state is never updated.  So, if you change the variables, then somehow get back to the original "variables" you will not get the correct results as the query will not re-execute. And any subsequent variables will always cause a re-query.

Suggestion:
In Query -> willReceiveProps

```
if (! shallowEqual(asJsObject(q##variables), asJsObject(state.variables))) {
        sendQuery(~query=q, ~reduce);
        {...state, variables: q##variables};
      }
```

This will allow it to execute properly.

PS Might be more worth the time/effort to start defining 2.1 support instead.

**Comment by Gregoirevda** [comment]
Published on npm
https://github.com/apollographql/reason-apollo/pull/60
