### ISSUE TITLE
Fails to find graphql schema

### ISSUE THREAD

**Issue by blackxored** [apollographql/reason-apollo#65]
**Issue Labels**

- [ ] has-reproduction
- [ ] feature
- [ ] docs
- [x] blocking
- [ ] good first issue

Graphql_ppx.Schema_file_not_found
File "/Users/blackxored/Code/src/github.com/blackxored/esk/src/core/Apollo.re", line 1:
Error: Error while running external preprocessor

I've downloaded graphql_schema.json and I've put it everywhere in my project, root, next to the Apollo.re, parent dir.

**Comment by Gregoirevda** [comment]
You should run `yarn send-introspection-query http://YOUR_GQL_API` at the root of your project. If that doesn't work, try to change something in your graphql query string (sometimes caching will prevent updates) if that doesn't work try deleting the `build` and `lib` and re-run your yarn commands

**Comment by blackxored** [comment]
I’ve already ran an introspection query with apollo-codegen, so I
definitely have an schema file ;).
I don’t even have a query string yet, just adding the ppx makes it blow.

-- 
Best Regards,

Adrian Perez
https://adrianperez.codes

**Comment by Gregoirevda** [comment]
Not sure if the introspectionQuery is the same: https://github.com/mhallin/graphql_ppx/blob/63f26556809385f832f0d2714cb6e5665a4001ce/sendIntrospectionQuery.js#L32
So I would try out `yarn send-introspection-query http://YOUR_GQL_API`

You could log `dir` in here: https://github.com/mhallin/graphql_ppx/blob/12be4aec081df6e8e12a81b48369e38195f69d6c/src/graphql_ppx.ml#L46

**Comment by blackxored** [comment]
Hmm that's so weird. Would you mind if I add this as a FAQ item or something that apollo-codegen wouldn't work?
I think most people would `apollo-codegen introspect-schema <url>` or `graphql get-schema <url>`, neither of which seem to work with this.
