### ISSUE TITLE
bool type vs Js.boolean type conflict?

### ISSUE THREAD

**Issue by idkjs** [apollographql/reason-apollo#67]
**Issue Labels**

- [x] [has-reproduction](https://github.com/idkjs/bool-vs-jsboolean)

I'm testing `reason-apollo@beta` and getting a type error when Im trying to pass the returned data to a component. Apparently, bs-platform 3.0 doesnt make a distinction between Js.boolean and bool types while ReasonApollo.response is returning a Js.boolean type, when i pass the parsed result to another component, that component assumes the type is `bool` which results in following type error. Fully explained in [reason.chat](https://reasonml.chat/t/bool-vs-js-boolean-in-reasonreact/506/6).

This doesn't work.[src/Feedpage.re](https://github.com/idkjs/bool-vs-jsboolean/blob/652d57c833806fd48b0aeec6d01f1d8b82c7a46a/src/components/FeedPage.re#L75)
```sh
This has type:
    array(Js.t(({.. id: string, isPublished: bool, text: string,
                  title: string}
                as 'a))) =>
    array(ReasonReact.reactElement)
  But somewhere wanted:
    Js.Array.t({. "id": string, "isPublished": Js.boolean, "text": string,
                 "title": string}) =>
    'b

  The incompatible parts:
    array(Js.t('a))
    vs
    Js.Array.t({. "id": string, "isPublished": Js.boolean, "text": string,
                 "title": string})
      (defined as
      array({. "id": string, "isPublished": Js.boolean, "text": string,
              "title": string}))
    at <anonymous> isPublished are incompatible
```

While the does. 
```
response##feed
                   |> Array.mapi((index, post) =>
                        <div key=(index |> string_of_int)>
                          (post##title |> ste)
                        </div>
                      )
                   |> ReasonReact.arrayToElement
```

I can't figure out why the type is changing which is preventing me from using the result of the boolean in a function. Ideas? Thank you.

**Comment by idkjs** [comment]
Solution here: https://reasonml.chat/t/bool-vs-js-boolean-in-reasonreact/506/21?u=idkjs

**Comment by Gregoirevda** [comment]
I was reading the thread yesterday evening. Seems annoying, but more specific to Reason. If I upgrade to bs-platform 3.0, will 2.x have problems?

**Comment by Gregoirevda** [comment]
Yeah I also had a lot of warnings in bs-react-native when using bs-platform 3.0.0, so made this PR: https://github.com/reasonml-community/bs-react-native/pull/172

But apparently it is a breaking change for projects using bs-platform 2.0.0. Don't really know what to do with it

**Comment by idkjs** [comment]
Anything i can do to help, on anything, really, i'm willing. Anything?
