### ISSUE TITLE
Using CreateQuery to get data only.

### ISSUE THREAD

**Issue by idkjs** [apollographql/reason-apollo#71]
This library is intended for use of react-apollo in reason. Should I be writing additional bindings to just query data without sending it to the UI?

For example, using the swapi example in [feature/react-apollo2.1](https://github.com/apollographql/reason-apollo/tree/feature/react-apollo-2.1/examples/swapi)

Can I do something like:

```
module GetAllPersons = [%graphql
  {|
    query getAllPersons {
      allPersons {
        id
        age
        name
      }
    }
|}
];
let client = Client.apolloClient(apolloClientOptions);

let personsQuery = GetAllPersons.make();

let query = personsQuery##query;

Js.log(query);

let persons = gql({|
    {
        query
    }
|});

let options = {"query": persons};

let testing =
  Js.Promise.(
    resolve(client##query(options))
    |> then_(response => {
         let data = response##data;
         Js.log2("TESTING", data);
         resolve();
       })
  );
```
Thanks.

**Comment by Gregoirevda** [comment]
You can use `ApolloConsumer `

```reason
<ApolloConsumer
>
  ...((client) => {
    Js.Promise.(
        resolve(client##query({
         "query": personsQuery##query
          "variables": personsQuery##variables
     }))
     |> then_(res => {
           Js.log(res);
      })
  })
</ApolloConsumer>
```

Thought, looking at the client signature I realise it returns a React.component, but should be a Promise

**Comment by idkjs** [comment]
Thank you, very much, sir. I was trying to work with that but was probably looking at it too long. Thanks for the example.

**Comment by svoynow** [comment]
@idjks Did this work for you? I end up with data inside my `then` handler and according to the logging it has the structure you would expect (`data`, `loading` etc.). But if I try to access the fields (i.e. `res##data` or similar), I get a type error complaining that the return type of `query` is `string` not an object with the field `data`

**Comment by idkjs** [comment]
@svoynow I did not end up using this. The thing i was trying to do was use the query component as a data only component. I realized that if i just return the data, I could pass it to whatever other component without doing any ui. So that is what ended up happening. At any rate, library has been progressing so I dont even know if that code is still valid. Peace to you, brother.
