### ISSUE TITLE
The module or file ReasonApollo.CreateClient can't be found.

### ISSUE THREAD

**Issue by mattferrin** [apollographql/reason-apollo#73]
I've tried to use this project twice at different times for different personal projects and I've always received the error below after following the readme:

  19 │ 
  20 │ module Client =
  21 │   ReasonApollo.CreateClient(
  22 │     {
  23 │       let apolloClient =
  
  The module or file ReasonApollo.CreateClient can't be found.
  - If it's a third-party dependency:
    - Did you list it in bsconfig.json?
    - Did you run `bsb` instead of `bsb -make-world`
      (latter builds third-parties)?
  - Did you include the file's directory in bsconfig.json?

I'm sure I follow the instructions perfectly. What can I do? I'm new to Reason.

**Comment by Nemak121** [comment]
It seems that `npm install reason-apollo` or `yarn add reason-apollo` install the **0.7.3-beta** version by default. ( You can check that out in your package.json ). 
I'm not sure but I think the 0.7.3-beta version corresponds to the [react-apollo-2.1 branch](https://github.com/apollographql/reason-apollo/tree/feature/react-apollo-2.1). 
If that's the case following readme from the[ react-apollo-2.1 branch](https://github.com/apollographql/reason-apollo/tree/feature/react-apollo-2.1) should be the way to go :).
Hope that helps !

**Comment by mattferrin** [comment]
I haven't added queries and mutations yet, but this worked perfectly to resolve my compilation errors! Thank you.

**Comment by Gregoirevda** [comment]
I merged the branch into master, which now displays the correct README
