### ISSUE TITLE
Mutation documentation

### ISSUE THREAD

**Issue by happylinks** [apollographql/reason-apollo#77]
Hi,

It seems like the documentation for mutations in the readme is incomplete and/or not working. I tried to fix it but couldn't get it working with the different types of the "result" param.

Will try some more tomorrow but if someone can gives a hint, would be very much appreciated!

Michiel

**Issue Labels**

- [ ] has-reproduction
- [ ] feature
- [X] docs
- [ ] blocking
- [ ] good first issue

**Comment by Gregoirevda** [comment]
Hey @happylinks I'm sorry for not making this clear in the README!
Just updated the README: https://github.com/apollographql/reason-apollo/commit/ef95379ab551c2183ae50c7a665045ad13acd66a

**Comment by Gregoirevda** [comment]
You can find an example in `examples/swapi` if you're still blocked with something else

**Comment by happylinks** [comment]
Thanks, this makes it a bit clearer already! But the thing I was mostly curious about was the result param:
https://github.com/apollographql/reason-apollo/blob/master/examples/swapi/src/AddPerson.re#L22
You define it as "_" here and ignore it, but if I'm correct it has 4 types (the ones mentioned here: https://github.com/apollographql/reason-apollo/blob/master/src/graphql-types/ReasonApolloMutation.re#L63-L67)

But when I make a switch on the result and then see which of these types it is, it doesn't recognize them.

If you could make an example which includes that as well then everything is 100% complete :)

**Comment by Gregoirevda** [comment]
This should work
```
(mutation, {result}) => {
 switch result {
 | Called => <div> ("Called" |> ste) </div>
 | Loading => <div> ("Loading" |> ste) </div>
 | Error(err) => <div> ("Error" |> ste) </div>
  | NoData => <div> ("NoData" |> ste) </div>
 | Data(data) => <div> ("Data" |> ste) </div>
 }
}
```

As you've seen here: https://github.com/apollographql/reason-apollo/blob/master/src/graphql-types/ReasonApolloMutation.re#L63-L67
We're making assumptions on the general use cases.
I you want a more fine grained access, you can use `data`

If you did deconstruct the `result`, then I'll have to dig in more

**Comment by happylinks** [comment]
Ahh it was indeed the deconstructing I forgot! Would you like me to make a PR to the docs to include this in the Pokemon example?
