### ISSUE TITLE
updateQuery for fetchMore

### ISSUE THREAD

**Issue by jeffutter** [apollographql/reason-apollo#79]
**Issue Labels**

- [ ] has-reproduction
- [x] feature
- [x] docs
- [ ] blocking
- [ ] good first issue

I'm not sure if I'm missing something here, but it seems like `fetchMore` queries require an `updateQuery` function to be passed to them to determine how to get the new set of results based on the original query and the update. All of the examples here use them: https://www.apollographql.com/docs/react/features/pagination.html .

Is there some other way to achieve this with reason-apollo or is it just missing the from the type and bindings?

Also, my application throws this error:

```Error: updateQuery option is required. This function defines how to update the query data with the new results.```

**Comment by Gregoirevda** [comment]
@jeffutter this should be added to the bindings!

```javascript
fetchMore({
            variables: {
              offset: data.feed.length
            },
            updateQuery: (prev, { fetchMoreResult }) => {
              if (!fetchMoreResult) return prev;
              return Object.assign({}, prev, {
                feed: [...prev.feed, ...fetchMoreResult.feed]
              });
            }
          })
```

We currently have this:
```reason
fetchMore: (~variables) =>
      apolloData##fetchMore({
          "variables": variables,
          "query": graphqlQueryAST,
}),
```

But should have:
```reason
fetchMore: (~variables, ~updateQuery: updateQuery) =>
      apolloData##fetchMore({
          "variables": variables,
          "query": graphqlQueryAST,
          "updateQuery": updateQuery
 }),
```

With `updateQuery` type definition that needs to be defined at the beginning of the module :
```
type updateQuery = (~previousResult: renderPropObj, ~nextResult: renderPropObj) => Js.t;
```
Not sure if previousResult === renderPropObj, but just `data, loading, error` (in that case those 3 types should be extracted from the type) Same for fetchMoreResult.

**Comment by jeffutter** [comment]
@Gregoirevda Thanks for the direction. I think I have this somewhat implemented over at: https://github.com/apollographql/reason-apollo/pull/99

However, I'm running into an error: 

```
index.js:2178 TypeError: mapFn is not a function
    at ObservableQuery.js:328
    at tryFunctionOrLogError (errorHandling.js:3)
    at ObservableQuery.updateQuery (ObservableQuery.js:327)
```

It's coming from apollo-client. I think I'm not passing the correct thing as the function sometimes, but I don't see how that could be happening. Do you see anything obviously wrong over there?

**Comment by studious** [comment]
I'm keenly following this one because I am hopeful the work here will make a binding easier to implement on the Query component for subscribeToMore which works in a similar manner. It takes `document` a gql template string like `query` in fetchMore and the `updateQuery` function and returns an unsubscribe function. 

https://www.apollographql.com/docs/react/api/react-apollo.html#graphql-query-data-subscribeToMore

**Comment by Gregoirevda** [comment]
subscribeToMore is already implemented here: https://github.com/apollographql/reason-apollo/blob/feature/Query-subscribeToMore/src/graphql-types/ReasonApolloQuery.re#L37. 
I need to merge everything together.
You can already use it under reason-apollo@alpha :)
