### ISSUE TITLE
Pattern matching for a mutation result is not correct

### ISSUE THREAD

**Issue by emmenko** [apollographql/reason-apollo#81]
**Issue Labels**
- [x] has-reproduction
- [x] bug
- [x] blocking

I noticed that the pattern matching for the mutation result is not quite correct.

https://github.com/apollographql/reason-apollo/blob/master/src/graphql-types/ReasonApolloMutation.re#L63-L67

```reason
switch (
  apolloData##called |> Js.to_bool,
  apolloData##loading |> Js.to_bool,
  apolloData##data |> ReasonApolloUtils.getNonEmptyObj,
  apolloData##error |> Js.Nullable.to_opt
) {
| (true, false, _, _) => Called
| (_, true, _, _) => Loading
| (false, false, Some(data), None) => Data(Config.parse(data))
| (false, false, _, Some(error)) => Error(error)
| (false, false, None, None) => NoData
```

#### Mutation execution flow
https://github.com/apollographql/react-apollo/blob/master/src/Mutation.tsx#L165-L179

The initial `state` is 

```js
{
  loading: false,
  called: false,
  error: undefined,
  data: undefined,
}
```

When the mutation is being executed, the state transitions first to: (`onStartMutation`)

```js
{
  loading: true,
  called: true,
  error: undefined,
  data: undefined,
}
```

Then we have either `onCompletedMutation` or `onMutationError`. In both cases the `loading` is set to `false` and either `data` or `error` are filled up.

⚠️ **However, `called` still remains to `true`**

#### Pattern matching problem

So if we look at the pattern matching, we clearly see that `Data`, `Error` and `NoData` assume `called` to be `false`, which is wrong. Additionally, a variant for the "initial" state is also missing in my opinion.

#### Proposed solution

We should add a new variant called e.g. `NoCalled` (which reflects the initial state). The pattern matching should be then fixed as following:

```reason
| (false, false, _, _) => NotCalled
| (true, false, Some(data), _) => Data(Config.parse(data))
| (true, false, _, Some(error)) => Error(error)
| (true, false, None, None) => NoData
| (true, _, _, _) => Called
| (_, true, _, _) => Loading
```

**Comment by emmenko** [comment]
I tested this in my app and it indeed fixes the problem. I'll spin up a PR to fix this if you want.

**Comment by emmenko** [comment]
Also it would good to extend the examples to make use of the "mutation result" with pattern matching.

And it would probably be good to start writing some tests 😇

**Comment by ng-marcus** [comment]
👍 I have the same problem, and this looks like a good fix

**Comment by Gregoirevda** [comment]
Fix has been published on npm `reason-apollo@latest`. I'm closing this
