### ISSUE TITLE
graphql_ppx 0.2.2 is a breaking change

### ISSUE THREAD

**Issue by ng-marcus** [apollographql/reason-apollo#85]
After updating to graphql_ppx  0.2.2 all of my graphql code failed to compile with an error about missing argument query.

The graphql_ppx change from 0.2.1 to 0.2.2 is says it "rename(d) "query" variable to avoid name clashes" so I think this is the breaking change.

**Comment by Gregoirevda** [comment]
You're right! I'll keep a CHANGELOG history from this version and tag version bump with changelog

**Comment by Gregoirevda** [comment]
Didn't read the error well. Thanks for sharing, what's the new variable name? Could you add something about that in the docs?

**Comment by emmenko** [comment]
It seems that they are going to “un-break” this. https://github.com/mhallin/graphql_ppx/issues/29#issuecomment-390626984

Let’s wait maybe if this is fixed upstream

**Comment by Coobaha** [comment]
@ng-marcus its fixed in 0.2.3
