### ISSUE TITLE
Record type for "apolloError##networkError" is not correct

### ISSUE THREAD

**Issue by emmenko** [apollographql/reason-apollo#88]
**Issue Labels**

- [x] has-reproduction
- [x] blocking
- [x] bug

In the `ReasonApolloTypes` we started [expanding apollo error](https://github.com/apollographql/reason-apollo/commit/19a5e7fc5224ce7c2fbf9f99bfe0854d67d2770d).

However, the `networkError` field is typed as `string`. It should be an object with more specific fields instead.

```reason
/* before */
type networkError = {. "statusCode": int}; /* <-- already existing */

type apolloError = {
  /* omitting some fields for simplicity */
  "networkError": Js.Nullable.t(string) /* <-- this should not be a string */
};

/* after */
type errorObj = {. "message": string};

type networkErrorResult = {. "errors": Js.Nullable.t(array(errorObj))};

type networkError = {
  .
  "statusCode": int,
  "result": networkErrorResult
}; /* <-- already existing */

type apolloError = {
  /* omitting some fields for simplicity */
  "networkError": Js.Nullable.t(networkError)
};
```

Now this is where it might get trickier: the `networkErrorResult` I assume depends on what kind of response the server will send. In the example above, I assume the server returns a "graphql-like" error response (e.g. a 400 validation error in case the query is wrong).

I suppose that we could model this in a more generic way, using an abstract type:

```reason
type networkErrorResult;

type networkError = {
  .
  "statusCode": int,
  "result": networkErrorResult;
};
```

This way we don't make any assumptions about the shape of the `result` and let the consumer type it.

```reason
type errorObj = {. "message": string};

type myOwnResult = {. "errors": Js.Nullable.t(array(errorObj))};

external toMyOwnResult = 'a => myOwnResult = "%identity";

/* usage */
toMyOwnResult(networkError##result);
```

Is there any other way of doing this properly? Does it even make sense of doing it? How do you usually handle those kind of network errors? Do you just log them?

**Comment by Gregoirevda** [comment]
https://github.com/apollographql/reason-apollo/pull/112 merged

**Comment by couchemar** [comment]
This error still actual: https://github.com/apollographql/reason-apollo/blob/master/src/ReasonApolloTypes.re#L64

Also we have two different kind of errors:
https://github.com/apollographql/reason-apollo/blob/master/src/ReasonApolloTypes.re#L49-L52
and https://github.com/apollographql/reason-apollo/blob/master/src/ReasonApolloTypes.re#L60-L64
