### ISSUE TITLE
Add example of @bsRecord

### ISSUE THREAD

**Issue by Gregoirevda** [apollographql/reason-apollo#92]
- [x] docs
- [x] good first issue

It would be good to show an example of the `@bsRecord` directive graphql_ppx exposes.
And show how to handle nested patterns on the response to avoid too many pattern matching on the response.
https://reasonml.github.io/docs/en/pattern-matching.html#nested-patterns

```
type hero = {
  name: string,
  height: number,
  mass: number
};

module HeroQuery = [%graphql {|
{
  hero @bsRecord {
    name
    height
    mass
  }
}
|}];
```

**Comment by emmenko** [comment]
Ah yeah, good idea! That was one of the "pain" points in the Dojo session at the ReasonConf for many people starting with Reason (the Github GraphQL API didn't help much in that case 😅)

**Comment by Gregoirevda** [comment]
Yeah, I'm working on this on graphql_ppx... this is part of the 1.0.0 goal

**Comment by emmenko** [comment]
Nice. So does it mean that we will get records from the ppx? Or, in case we want to use records, we still need to define them ourselves? 🤔

**Comment by emmenko** [comment]
Btw: would you like to define the 1.0.0 milestone? (e.g. as an issue, to keep track of what is missing to get there).

**Comment by arecvlohe** [comment]
This is awesome! I went from this:
```
let title = switch response##link {
  | Some(obj) => obj##title
  | None => ""
};
let url = switch response##link {
  | Some(obj) => switch obj##url {
                 | Some(url) => url
                 | None => ""
                 }
  | None => ""
};
```

To this:
```
let (title, url) =
  switch response##link {
  | Some({title, url: Some(url)}) => (title, url)
  | Some({title, url: None}) => (title, "")
  | None => ("", "")
};
```

`@bsRecord` FTW!

Here is my query and stuff:
```
type link = {
  id: string,
  title: string,
  url: option(string)
};

module GetLink = [%graphql
  {|
    query getQuery($id: ID!) {
      link: Link(id: $id) @bsRecord {
        id
        title
        url
      }
    }
  |}
];
```

**Comment by arecvlohe** [comment]
Added in #109
