### ISSUE TITLE
Explanation/Decoding Optional Responses?

### ISSUE THREAD

**Issue by idkjs** [apollographql/reason-apollo#98]
I'm wondering why the following code, which is basically the same as the `examples/swapi` example, is throwing the options error when it doesnt do it for the swapi code. Two things I can see is that in the `examples/swapi` the person type used implements node. 

The question is why does reason-apollo handle these differently?

Also, how do I decode the response given the error. 

[repo](https://github.com/idkjs/reason-apollo-question) with this example code.

This is the type in this example:
```
type Person {
  age: Int!
  id: ID!
  name: String!
}
// type from `examples/swapi`
type Person implements Node {
  age: Int!
  id: ID!
  name: String!
}
```
Running a query:
```
   module GetAllPersons = [%graphql
     {|
       query GetList {
         listPeople {
           items {
             age
             id
             name
           }
         }
       }
   |}
   ];
```

Response:

```
{
  "data": {
    "listPeople": {
      "items": [
        {
          "age": 23,
          "id": "123",
          "name": "BobTest"
        },
        {
          "age": 24,
          "id": "124",
          "name": "JoeTest"
        },
        {
          "age": 25,
          "id": "125",
          "name": "JimTest"
        }
      ]
    }
  }
}
```

In the component, i'm trying to us it like so:

```
let make = _children => {
  ...component,
  render: _self =>
    <GetAllPersonsQuery>
      ...(
           ({result}) =>
             <div>
               <h1> ("Persons: " |> ste) </h1>
               (
                 switch (result) {
                 | Error(e) =>
                   Js.log(e);
                   "Something Went Wrong" |> ste;
                 | Loading => "Loading" |> ste
                 | Data(response) =>
                   response##listPeople##items
                   |> Array.mapi((index, person) =>
                        <div key=(index |> string_of_int)>
                          (person##name |> ste)
                          <br />
                          <p> ("ID: " ++ person##id |> ste) </p>
                        </div>
                      )
                   |> ReasonReact.array
                 }
               )
             </div>
         )
    </GetAllPersonsQuery>,
};
```

This generates the following error:

```bash
  We've found a bug for you!
  /Users/prisc_000/code/REASON/APOLLO/reason-apollo-question/src/Persons.re 36:20-39

  34 ┆ | Loading => "Loading" |> ste
  35 ┆ | Data(response) =>
  36 ┆   response##listPeople##items
  37 ┆   |> Array.mapi((index, person) =>
  38 ┆        <div key=(index |> string_of_int)>

  This has type:
    option({. "items": option(Js.Array.t(option({. "age": int, "id":
                                                  string, "name": string})))})
  But somewhere wanted:
    Js.t('a)

[4/6] Building ient-ReactTemplate.cmj
ninja: build stopped: subcommand failed.
>>>> Finish compiling(exit: 1)
```
I was going to post this to stackoverflow after making just a decode question.
Thanks for the clarification.

**Comment by Gregoirevda** [comment]
Isn't it because `listPeople ` is an option and you try to access items immediately (`##items`)?

**Comment by Gregoirevda** [comment]
Did you `yarn send-introspection-query http://my-api.example.com/api && yarn clean && yarn start`?

**Comment by idkjs** [comment]
This endpoint is an AWS endpoint. I did not run the introspection query because I could not figure out how to run it against AWS and then came upon [get-introspection-schema](https://docs.aws.amazon.com/ja_jp/cli/latest/reference/appsync/get-introspection-schema.html) in the aws appsync docs. So I ran:

`aws appsync get-introspection-schema --api-id pdtqkhbx3nawtfg5lody6w6jcu --format JSON graphql_schema.json`

I tried passing the endpoint and app-id to send-intro-query unsuccessfully
```
    "get-schema":
      "yarn send-introspection-query https://nkdhnplh2vebvfgjvz3pbbagli.appsync-api.eu-west-1.amazonaws.com/graphql --api-id pdtqkhbx3nawtfg5lody6w6jcu"
  },
```
output:
```
$ /Users/prisc_000/code/REASON/APOLLO/reason-apollo-question/node_modules/.bin/send-introspection-query https://nkdhnplh2vebvfgjvz3pbbagli.appsync-api.eu-west-1.amazonaws.com/graphql --api-id pdtqkhbx3nawtfg5lody6w6jcu
Non-ok status code from API:  401 Unauthorized
error Command failed with exit code 1.
```

I guess I made the assumption that it was working because the queries were logging and the graphql/ppx was checking against it. 

Am I going about this incorrectly?

Thank you for the guidance.

**Comment by Gregoirevda** [comment]
In the last README section there's a note on that. Seems like the introspection query provided by graphql_ppx doesn't give the same response as others. I'd be interesting too see a diff of the JSON.

**Comment by idkjs** [comment]
Aware of that note. I guess the question is how do we deal with that? Thinking out loud here. So the ppx introspection query returns something different. Checking the introspection query in aws-appsync-codegen vs graphqlppx, it looks the same. See [this repo](https://github.com/idkjs/compare-introspection). 

So maybe that isn't the issue.  What do you think?

**Comment by idkjs** [comment]
Update: 
I tried parsing the response [here](https://github.com/idkjs/reason-apollo-question/blob/600584c454ffb2efd08b8e42e3adca0eb151ba60/src/Persons.re#L20)

This is the type for `response##listPeople`
```
option({. 
"items": option(Js.Array.t(
   option({. "age": int, "id": string, "name": string})))
})
```
![screen shot 2018-05-28 at 12 19 18 pm](https://user-images.githubusercontent.com/2370391/40610180-a07a6c60-6271-11e8-83e8-84f5d66594b4.png)

But then when you try to parse this you get this error:

```
We've found a bug for you!
  /Users/prisc_000/code/REASON/APOLLO/reason-apollo-question/src/PersonsScratch.re 197:49-58

  195 ┆ Js.log(response##listPeople);
  196 ┆ let listPeople = response##listPeople;
  197 ┆ let parsedItems = parseItems(listPeople);
  198 ┆ Js.log(parsedItems);
  199 ┆ <div> <h1> (ReasonReact.string("TEST")) </h1> </div>;

  This has type: //object record
    option({. "items": option(Js.Array.t(option(
    {. "age": int, "id":string, "name": string})))
    })

  But somewhere wanted: //closed object record
    option({.. "items": option(array(option(Js.t(
     ({.. age: option(int),
          id: option(string),
          name: option(string)
       } as 'a)))))
     })

  The incompatible parts:
    Js.Array.t(option({. "age": int, "id": string, "name": string})) 
      (defined as
      array(option({. "age": int, "id": string, "name": string}))) 
    vs
    array(option(Js.t('a)))
  Types for method age are incompatible

ninja: build stopped: subcommand failed.
>>>> Finish compiling(exit: 1)
```

Note that in 'incompatible parts' you are getting the `{{. "age:` single dot for a closed object record.

Its looking for `{.. "items"` syntax for a closed record.

`item##name`, `item##age` and `item##id` are typed as closed records :

```
Js.t(({.. age: option(int), id: option(string), name: option(string)} as 'a)) =>
'a
```

I'm kind of guessing but are we doing something wrong here?
https://github.com/apollographql/reason-apollo/blob/b9631b1de19387047f72d852ea91694de6174b6c/src/ReasonApolloUtils.re#L1-L13

How do I resolve this error?

**Comment by idkjs** [comment]
Solution:

https://github.com/idkjs/reason-apollo-question/blob/2924b1eb928cf0e4de57d5659c5da1bed4dd981c/src/Persons.re#L31-L33

Basically, i had not grocked Some/None variables yet. Thanks for feedback.
